-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 20, 2023 at 01:52 PM
-- Server version: 10.4.25-MariaDB
-- PHP Version: 8.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `dbdramaindonesia`
--

-- --------------------------------------------------------

--
-- Table structure for table `drama`
--

CREATE TABLE `drama` (
  `id_drama` int(11) NOT NULL,
  `gambar` varchar(512) DEFAULT NULL,
  `judul` varchar(512) DEFAULT NULL,
  `genre` varchar(512) DEFAULT NULL,
  `tanggal_tayang` varchar(512) DEFAULT NULL,
  `sinopsis` text DEFAULT NULL,
  `sutradara` varchar(512) DEFAULT NULL,
  `pemeran` varchar(512) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `drama`
--

INSERT INTO `drama` (`id_drama`, `gambar`, `judul`, `genre`, `tanggal_tayang`, `sinopsis`, `sutradara`, `pemeran`) VALUES
(1, 'Anak-jalanan.jpeg', 'Anak Jalanan', 'Drama Roman Laga', '2015-10-12', 'Anak Jalanan: A New Beginning menceritakan tentang seorang anak geng motor bernama Boy yang jatuh cinta dengan seorang gadis bernama Reva Semenjak bertemu dengan Reva hidupnya berubah namun kisah cinta mereka tidak berjalan mulus dengan banyaknya tantangan dari orang-orang di sekitarnya.', 'Akbar Bhakti', 'Natasha Wilona. Ammar Zoni. Cut Meyriska. Immanuel Caesar Hito. Raya Kitty. Ranty Maria. Marcella Daryanani. Gerald Yo. Angga Putra. Cemal Faruk. Mischa Chandrawinata. Hana Saraswati. Adipura.Umar Lubis. Fathir Muchtar. Yoelitta Palar. Devi Permatasari. Meriam.'),
(2, 'Ayat-Ayat_Cinta.jpg', 'Ayat-Ayat Cinta', 'Roman Drama', '2008-02-28', 'Ini adalah kisah cinta. Tapi bukan cuma sekadar kisah cinta yang biasa. Ini tentang bagaimana menghadapi turun-naiknya persoalan hidup dengan cara Islam. Fahri bin Abdillah adalah pelajar Indonesia yang berusaha menggapai gelar masternya di Al-Azhar. Berjibaku dengan panas-debu Mesir. Berkutat dengan berbagai macam target dan kesederhanaan hidup. Bertahan dengan menjadi penerjemah buku-buku agama. Semua target dijalani Fahri dengan penuh antusias kecuali satu: menikah.Fahri adalah laki-laki taat yang begitu', 'Hanung Bramantyo', 'Fedi Nuril. Rianti Cartwright. Carissa Putri. Zaskia Adya Mecca. Melanie Putria. Surya Saputra. Oka Antara. Dennis Adhiswara'),
(3, 'Bintang-DiHatiku.jpg', 'Bintang di Hatiku', 'Drama Keluarga', '2017-04-03', 'Murti Intan Nuraini merupakan ibu dari empat orang anak yang bernama Selly Bagus Poppy dan Lolly. Ia berjumpa dengan Jaka (Sonny Septian) yang mengatakan akan menikahinya dan menerima keempat anak-anak Murti. Jaka pada suatu hari meminta Murti untuk hadir ke Jakarta sendirian. Murti kemudian meninggalkan anak-anaknya bersama ibu Murti di desa. Namun Jaka menyuruh seseorang untuk membakar rumah Murti tersebut sehingga menyebabkan ibu Murti meninggal. Keempat anaknya kemudian berangkat ke Jakarta untuk mencar', 'Bobby Moeryawan', 'Intan Nuraini. Haura Lathifa. Jerico Septian Gowtama. Ciara Brosnan. Aditya Firmansyah. Sonny Septian. Adelia Rasya. Nisya Ahmad. Teuku Mirza. Rayhan Cornelis'),
(4, 'Cinta_Fitri_New.jpg', 'Cinta Fitri', 'Drama Roman Keluarga Religi', '2007-04-02', 'Cinta Fitri menjadi salah satu sinetron kebanggaan yang ditayangkan oleh stasiun televisi SCTV kemudian pindah ke Indosiar karena alur ceritanya yang padat menarik dan kadang-kadang tidak terduga apa lanjutannya. Ini juga menjadi kunci kesuksesan Cinta Fitri sehingga bisa bertahan hingga musim ke 7 dan tayang selama 4 tahun dari tahun 2007 hingga 2011 dan walaupun setelah Cinta Fitri Season Ramadhan selesai tayang beberapa orang mulai mengkritik jalan cerita Cinta Fitri yang terlihat semakin dibuat-buat dan', 'H. Encep Masduki', 'Shireen Sungkar. Teuku Wisnu. Adly Fairuz. Donita. Verlita Evelyn. Iqbal Pakula. Dinda Kanyadewi. Sandy Syarief. Nuri Maulid. Lian Firman. Irene Librawati. Meidiana Hutomo'),
(5, 'Cinta_karena_Cinta.jpg', 'Cinta karena Cinta', 'Drama Roman ', '2019-08-01', 'Kisah bermula dari Jenar kembali bermimpi tentang kejadian kebakaran di rumahnya 15 tahun yang lalu. Ayah dan ibunya Halim dan Sriningsih tewas dalam peristiwa tersebut. Jenar juga mengira bahwa kakaknya Mila tewas dalam kejadian tersebut padahal kakaknya itu terluka parah dan diadopsi oleh Ayu yang kemudian namanya diganti menjadi Raisa.', 'Gita Djun', 'Natasha Wilona. Immanuel Caesar Hito. Gabriella Larasati. Megan Domani. Adjie Pangestu. Dina Lorenza. Rexy Rezky. Nunu Datau. Boy Tirayoh. Cut Keke. Inggrid Kansil. Reza Ali Syahbana. Sandrinna Michelle. Ersya Aurelia. Philip de May. Dinda Kanyadewi. Eeng Saptahadi. Triningtyas.'),
(6, 'Dunia_Terbalik.jpeg', 'Dunia Terbalik', 'Komedi Drama', '2017-01-05', 'Dunia Terbalik mengangkat cerita tentang para suami yang ditinggalkan istrinya untuk bekerja di luar negeri. Dimulai dari kisah Akum Aceng Idoy dan Dadang. Mereka harus mendidik anak dan mengurus urusan rumah tangga yang biasanya menjadi urusan para wanita. Sementara istrinya harus menafkahi keluarga.', 'Iip S. Hanan. Depi Herlambang. Lono Abdul Hamid. Rudi Aryanto. Indrawan. Bobby Herlambang. Asep Kusdinar', 'Agus Kuncoro. Sutan Simatupang. Bambang Chandra Bayu. Indra Birowo. Mieke Amalia. Diaz Ardiawan. Guntara Hidayat. Anjani Dina. Valerie Tifanka. Rosnita Putri. Idrus Madani. Ryana Dea. Mak Enah. Faby Marcelia. Annisa Shifa MH. Qheyla Valendro. Yafi Tessa Zahara. Marsha Risdasari.'),
(7, 'Csuperboy.jpeg', 'Cowokku Superboy', 'Drama Roman', '2014-11-16', 'Elang atau akrab dipanggil El Ciccio Manassero adalah seorang remaja berusia 17 tahun yang bersekolah di SMU Amanah. Sekilas El terlihat seperti remaja lain seusianya tetapi El ternyata memiliki kekuatan rahasia yang maha dahsyat. Hanya kedua orang tua El yaitu Tyas Angel Karamoy dan Adam Mike Lewis yang mengetahui kekuatan ini.', 'Emil G Hampp', 'Ciccio Manassero. Larasati Nugroho. Belinda Camesi. Christ Laurent. Mikaila Patritz.'),
(8, 'Ganteng-Ganteng_Serigala.jpg', 'Ganteng-Ganteng Serigala Langit', 'Drama Laga Misteri Horror Remaja', '2014-04-21', 'Tristan bersama saudara-saudaranya adalah murid baru di salah satu International School. Tak ada yang tahu bahwa Tristan dan saudara-saudaranya yaitu Digo Yasha Liora dan Thea adalah bangsa vampir. Ayah mereka yaitu Ayah Agra mengutus Tristan untuk mencari dan mengambil darah suci yang terdapat dalam tubuh Nayla. Bila bangsa vampir mendekati pemilik darah suci mereka akan merasa kesakitan. Oleh sebab itu ayah Agra mengutus Tristan untuk mengambil darah suci itu karena Nayla sudah jatuh cinta kepada Tristan ', 'Findo Purwono HW', 'Ricky Harun. Jessica Mila. Kevin Julio. Aliando. Dicky SM*SH. Prilly Latuconsina. Dahlia Poland. Michelle Joan. Ricky Cuaca.'),
(9, 'Hati_yang_Memilih.jpeg', 'Hati yang Memilih', 'Drama Roman Keluarga Fantasi', '2017-04-26', 'Hati yang Memilih bercerita tentang kisah seorang gadis bernama Putri yang sangat mandiri. Untuk mencari uang Putri bekerja sebaAzzam adalah seorang pemuda sederhana yang memilih untuk menuntut ilmunya di Kampus Universitas Al Azhar Kairo. Azzam dikenal sebagai sosok yang tegas dan dewasa. Dia sangat memegang teguh prinsip-prinsip Islam dalam kehidupan sehari-harinya. Di kalangan teman-temannya pun Azzam menjadi panutan dan sosok yang bisa diandalkan.', 'Bobby Moeryawan Encep Masduki', 'Amanda Manopo. Lucky Perdana. Aditya Zoni. Eza Gionino. Christ Laurent. Masayu Clara. Fadlan Muhammad. Verlita Evelyn. Susan Sameh. Rommy Sulastyo. Andi Soraya. Rebecca Tamara. Irene Librawati. Erma Zarina. Mat Rozi.'),
(10, 'Ketika_Cinta_Bertasbih.jpg', 'Kisah Cinta Bertasbih', 'Drama Roman', '2020-02-17', 'Diandra memiliki sifat baik hati lemah lembut dan penyayang. Ia dan adiknya Elsa hidup bahagia bersama sang ayah Harun. Namun semua itu berubah ketika Lena serta putrinya Clara masuk dalam kehidupan Diandra dan Elsa karena Harun menikahi Lena. Clara adalah gadis seusia Diandra yang memiliki tempramen suka merundung jahat iri dan tidak suka orang lain lebih darinya. Di hari pernikahan Harun dan Lena Diandra sengaja dikunci di kamar mandi.', 'Umam A.P.', 'Zoe Jackson. Aditya Zoni. Ochi Rosdiana. Icha Nabila. Dinda Mahira. Sultan Djorghi. Annisa Trihapsari. Hj. Nani Wijaya. Richelle. Sisca Magdalena. Achul Wiraperwata. Adzwa. Rizky Djanbi. Jeremie Moeremans. Indah Setyani.'),
(11, 'Melati_Untuk_Marvel.jpg', 'Melati untuk Marvel', 'Drama Roman', '2008-10-23', 'Melati gadis berusia 22 tahun jodoh adalah urutan ke sekian setelah pekerjaan. Melati sendiri adalah sosok yang mandiri tegas dan bertanggung jawab. Ditunjang oleh penampilan fisik yang menarik tak heran jika banyak cowok yang jatuh hati padanya.', 'Akbar Bhakti', 'Chelsea Olivia. Rezky Aditya. Christ Laurent. Neshia Putri. Fendy Chow. Gracia Indri. Afifa Syahira. Ryan Delon.'),
(12, 'Anak_Langit.jpeg', 'Anak Langit', 'Laga Roman Drama', '2017-02-20', 'Al Andra dan Key tinggal di Panti Asuhan milik Babe Rozak dan Nyak Ida. Mereka bertiga memiliki kepribadian yang berbeda tetapi saling melengkapi. Mereka tergabung dalam sebuah geng motor Rainbow. Salah satu anggota Rainbow bernama Reno yang telah meninggal menitipkan adiknya Vika kepada Al. Seiring berjalannya waktu Al menaruh hati pada Vika. Namun Rimba yang merupakan ketua geng motor Anthrax yang tak lain adalah musuh besar Al berusaha menarik hati Vika.', 'Akbar Bhakti', 'Stefan William. Marcella Daryanani. Hana Saraswati. Anthony Xie. Gerald Yo. Mario Maulana. Raya Kitty. Fathir Muchtar. Fera Feriska. Umar Lubis. Devi Permatasari. Angga Putra. Leon Dozan. Mezty Mez. Benny Ruswandi. Henny Timbul. Sasha Alexa. Merry Mustaf. Adipura. Aldo Bamar. Siska Magdalena. Firman Maliksyah. Audi Marissa. Fanny Fadillah. Cassandra Lee. George Rudy. Fendy Pradana. Kevin Kambey. Natalie Zenn. Esta Pramanita. Ije Kurniawan. Teuku Anwar. Willy Dozan.'),
(13, 'awas_ada_sule.jfif', 'Awas Ada Sule', 'Komedi Drama ', '2009-06-10', 'Rekomendasi serial komedi Awas Ada Sule di GTV menceritakan keseharian sebuah keluarga dan pembantu mereka yang tinggal bersama. Keluarga tersebut terdiri dari Pak Tio dan istrinya. Bu Tio serta orang tua mereka yang biasa dipanggil Kanjeng Mami. Mereka sendiri memiliki seorang pembantu serta supir yang bekerja di keluarga mereka yaitu Sule dan Makmur. Interaksi antara Sule pembantu yang riang dan Makmur  supir polos sebagai tokoh utama sering disorot dalam serial ini. Kekocakan dalam serial ini tidak hanya', 'E-Motion Entertainment', 'Hannah Al Rasyid. Tania Putri. Eko DJ. Astriana. Kang Uchi.'),
(14, 'Pangeran.jpg', 'Pangeran', 'Drama Roman Laga Fantasi Komedi Religi', '2015-08-10', 'Karena kenakalan nya Pangeran dipaksa ayahnya belajar di pesantren. Walaupun sering berbuat ulah dipesantren kedua putri Kyai Makmun Aida & Anjani diam-diam bersimpati kepada Pangeran. Saat pergi ke hutan Pangeran bertemu dengan Maung Bodas yang kemudian menyerahkan kalung berbentuk macan kepadanya. Maung Bodas menjelaskan Pangeran adalah titisan cucu Prabu Siliwangi. Kemunculan Pangeran juga membangkitkan Raden Mahesa musuh bebuyutan Prabu Siliwangi.', 'Ai Manaf', 'Ricky Harun. Fita Anggriani. Handika Pratama. Nina Zatulini. Teddy Syach. Rifat Sungkar. Reza Aditya. Rangga Boevier. Ananda George.'),
(15, 'Cahaya_Cinta.jfif', 'Cahaya Cinta', 'Drama', '2011-09-05', 'Cahaya Cinta dan Dewa masih kecil ketika ayah mereka Haryoga tewas dan seluruh harta kekayaannya dikuasai Camelia wanita kepercayaan Haryoga sendiri. Pada saat itu Siska ibu mereka berhasil lari menyelamatkan diri dari kejaran Camelia untuk menyelamatkan anak-anaknya. Naas rumah mereka habis terbakar. Tak ada bukti kebenaran yang tersisa dan anak-anak Siska hidup terpisah pisah.', 'Dhammo Punjabi. Manoj Punjabi.', 'Sandara Dewi. Chicco Jerikho. Ryana Dea. Estelle Linden. Christ Laurent. Teuku Ryan. Desy Ratnasari. Gunawan. Rama Michael. Helsi Herlinda. Nella Anne. Didi Junaidi.'),
(16, 'Mawar_dan_Melati.jpeg', 'Mawar dan Melati', 'Drama Roman', '2017-05-05', 'Berkisah tentang dua sosok bernama Mawar dan Melati yang merupakan anak kembar tak identik dari pasangan Aswin dan Intan. Kehidupan keluarga yang awalnya bahagia berubah seketika karena Mawar dan Melati terpaksa harus menjalani kehidupan secara terpisah setelah kedua orang tua mereka bercerai.', 'Desiana Larasati', 'Natasha Wilona. Dinda Hauw. Aliando Syarief. Marcel Chandrawinata. Nunu Datau. Sigit Hardadi. Femmy Permatasari. Ersya Aurel. Megan Domani. Yoelitta Palar. Umar Lubis. Tasya. Annisa Aurelia. Kanaya.'),
(17, 'Tukang_Ojek_Pengkolan.jpeg', 'Tukang Ojek Pengkolan', 'Drama keluarga Komedi', '2015-04-25', 'Di sebuah kampung di daerah Rawa Bebek yang berada di belakang gedung-gedung perkantoran Jakarta tinggal pasangan suami istri bernama Rojak dan Tati. Untuk mencari nafkah Rojak bekerja sebagai tukang ojek yang berpangkalan di ujung jalan masuk ke kampung. Bersama dua rekannya Purnomo yang berasal dari Semarang dan Sutisna yang aslinya dari Bandung.', 'Iip S Hanan. Violano Tenori. Harun Zein. Dodi Sanjaya. Acum. Dewo Dwipa. Dodi Sanjaya. Dillon Tanjung. Lakamayus.', 'Eza Yayang. Andri Sulistiandri. Furry Setya . Fitri Ayu Maresa . Ranty Purnamasari. Adhe Nurul. Erik Estrada. Fajar Gomez. Hamas Syahid. Vanda Rainy. Hami Diah . Anastasja Rina. Bogel Alkatiri. Otong Lalo. Suparman . Engkar Nori. Ni Made Monica. Natasha Rizka Sakila. Henry Chan. Sandi Maryana. Tanih Dugal. Eloy Maharani. Fairus Aliya. Jonathan Alvaro. Ahmad Januar.'),
(18, 'Siapa_Suruh_Datang_Jakarta.jpg', 'Siapa Suruh Datang Jakarta', 'Drama Roman Komedi', '2016-01-18', 'Cemen Ephy Ifa dan Bene berniat merajut mimpi mereka menjadi orang sukses di Jakarta. Bene langsung bekerja sebagai kernet Ephy dimasukan ke dalam sel tetapi ia malah senang karena dapat makan dan tinggal gratis. Sementara Cemen dan Ifa mendaftar kuliah di kampus SCA.', 'ony Gaokasak. Fajar Nugros. M Haikal.', 'Mas Cemen. Musdalifah Basri. Ephy Sekuriti. Bene Dion. Larasati Nugroho. Dahlia Poland. Fandy Christian. Fanny Fabriana. Ferry Maryadi. Arya Saloka.'),
(19, 'Andai_Ku_Tahu.jpg', 'Andai Ku Tahu', 'Drama Roman', '2007-06-12', 'Sinetron Ini menceritakan kisah cinta pada pandangan pertama yang dialami oleh Nico saat ia bertemu dengan seorang perempuan cantik Karina (Acha Septriasa). Namun sebelum mereka sempat berkenalan Karina pergi. Walau begitu Nico tak bisa menghilangkan rasa sukanya dan percaya bahwa cintanya pada Karina adalah cinta yang hanya terjadi satu kali dalam hidupnya.', 'Rapi Films', 'Raffi Ahmad. Acha Septriasa. Irwansyah. Inneke Koesherawati.'),
(20, 'Cinta_Kirana.jpg', 'Cinta Kirana', 'Drama Roman', '2008-05-10', 'Kirana adalah gadis berusia 18 tahun yang tinggal dengan neneknya Sita. Suatu hari Saat sedang mengantarkan Koran pada pelanggannya Kirana tertabrak mobil yang dikemudikan Galang. Karena Galang malah menertawakannya Kirana kehilangan emosi dan menampar Galang.', 'Lono Abdul Hamid. Usman Gumanti', 'Nia Ramadhani. Randy Pangalila. Tsania Marwa. Kiki Farrel. Revand Narya. Poppy Bunga. Arthur Tobing. Yati Surachman. Erly Ashy. Fitri Ayu. Emma Waroka.'),
(21, 'Cinta_7_Susun.jpg', 'Cinta 7 Susun', 'Drama Roman Komedi Musikal', '2013-01-28', 'Mengisahkan tentang kisah 7 dara PJ Atee Linzy Vanila Natly Mezty dan Grace yang berbeda sifat dan latar belakang. Mereka tinggal di Rumah Susun RT 7. Mereka semua akhirnya disatukan oleh kecintaan mereka terhadap musik yang terbentuk secara tidak sengaja dalam upaya untuk menyelamatkan tempat tinggal mereka dari penggusuran maka terbentuk grup musik Rusun Girlband. Namun Vanila memutuskan untuk pulang kampung dan tidak ikut berpartisipasi dalam grup tersebut namun Rusun Girlband membutuhkan 7 karakter suara. Tak lama kemudian Choki menyelamatkan Rusun Girlband dengan memboyong Uty adiknya yang datang dari kampung dengan hadirnya Uty maka terbentuklah 7icons.', 'Desiana Larasati. Dodi M. Surahman', 'Angela Tee. Grace. Mezty Mez. Natly. PJ. Linzy. T-Sha. Baim Wong. Raya Kohandi. Mischa Chandrawinata.');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `drama`
--
ALTER TABLE `drama`
  ADD PRIMARY KEY (`id_drama`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
