-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 02, 2023 at 07:17 PM
-- Server version: 10.4.25-MariaDB
-- PHP Version: 8.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `dbdramaindonesia`
--

-- --------------------------------------------------------

--
-- Table structure for table `drama`
--

CREATE TABLE `drama` (
  `id_drama` int(11) NOT NULL,
  `gambar` varchar(512) DEFAULT NULL,
  `judul` varchar(512) DEFAULT NULL,
  `genre` varchar(512) DEFAULT NULL,
  `tanggal_tayang` date DEFAULT NULL,
  `sinopsis` varchar(512) DEFAULT NULL,
  `sutradara` varchar(512) DEFAULT NULL,
  `pemeran` varchar(512) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `drama`
--

INSERT INTO `drama` (`id_drama`, `gambar`, `judul`, `genre`, `tanggal_tayang`, `sinopsis`, `sutradara`, `pemeran`) VALUES
(0, '', '', '', '0000-00-00', '', '', ''),
(1, '../css/assets/Anak_Langit.jpeg', 'Anak Langit', 'Drama Roman Laga', '2015-10-12', 'Anak Jalanan: A New Beginning menceritakan tentang seorang anak geng motor bernama Boy yang jatuh cinta dengan seorang gadis bernama Reva Semenjak bertemu dengan Reva hidupnya berubah namun kisah cinta mereka tidak berjalan mulus dengan banyaknya tantangan dari orang-orang di sekitarnya.', 'Akbar Bhakti', 'Natasha Wilona. Ammar Zoni. Cut Meyriska. Immanuel Caesar Hito. Raya Kitty. Ranty Maria. Marcella Daryanani. Gerald Yo. Angga Putra. Cemal Faruk. Mischa Chandrawinata. Hana Saraswati. Adipura.Umar Lubis. Fathir Muchtar. Yoelitta Palar. Devi Permatasari. Meriam.'),
(2, '../css/assets/Ayat-Ayat_Cinta.jpg', 'Ayat-Ayat Cinta', 'Roman Drama', '2008-02-28', 'Ini adalah kisah cinta. Tapi bukan cuma sekadar kisah cinta yang biasa. Ini tentang bagaimana menghadapi turun-naiknya persoalan hidup dengan cara Islam. Fahri bin Abdillah adalah pelajar Indonesia yang berusaha menggapai gelar masternya di Al-Azhar. Berjibaku dengan panas-debu Mesir. Berkutat dengan berbagai macam target dan kesederhanaan hidup. Bertahan dengan menjadi penerjemah buku-buku agama. Semua target dijalani Fahri dengan penuh antusias kecuali satu: menikah.Fahri adalah laki-laki taat yang begitu', 'Hanung Bramantyo', 'Fedi Nuril. Rianti Cartwright. Carissa Putri. Zaskia Adya Mecca. Melanie Putria. Surya Saputra. Oka Antara. Dennis Adhiswara'),
(3, '../css/assets/Bintang-Di-Hatiku.jpg', 'Bintang di Hatiku', 'Drama Keluarga', '2017-04-03', 'Murti Intan Nuraini merupakan ibu dari empat orang anak yang bernama Selly Bagus Poppy dan Lolly. Ia berjumpa dengan Jaka (Sonny Septian) yang mengatakan akan menikahinya dan menerima keempat anak-anak Murti. Jaka pada suatu hari meminta Murti untuk hadir ke Jakarta sendirian. Murti kemudian meninggalkan anak-anaknya bersama ibu Murti di desa. Namun Jaka menyuruh seseorang untuk membakar rumah Murti tersebut sehingga menyebabkan ibu Murti meninggal. Keempat anaknya kemudian berangkat ke Jakarta untuk mencar', 'Bobby Moeryawan', 'Intan Nuraini. Haura Lathifa. Jerico Septian Gowtama. Ciara Brosnan. Aditya Firmansyah. Sonny Septian. Adelia Rasya. Nisya Ahmad. Teuku Mirza. Rayhan Cornelis'),
(4, '../css/assets/Cinta_Fitri_New.jpg', 'Cinta Fitri', 'Drama Roman Keluarga Religi', '2007-04-02', 'Cinta Fitri menjadi salah satu sinetron kebanggaan yang ditayangkan oleh stasiun televisi SCTV kemudian pindah ke Indosiar karena alur ceritanya yang padat menarik dan kadang-kadang tidak terduga apa lanjutannya. Ini juga menjadi kunci kesuksesan Cinta Fitri sehingga bisa bertahan hingga musim ke 7 dan tayang selama 4 tahun dari tahun 2007 hingga 2011 dan walaupun setelah Cinta Fitri Season Ramadhan selesai tayang beberapa orang mulai mengkritik jalan cerita Cinta Fitri yang terlihat semakin dibuat-buat dan', 'H. Encep Masduki', 'Shireen Sungkar. Teuku Wisnu. Adly Fairuz. Donita. Verlita Evelyn. Iqbal Pakula. Dinda Kanyadewi. Sandy Syarief. Nuri Maulid. Lian Firman. Irene Librawati. Meidiana Hutomo'),
(5, '../css/assets/Cinta_karena_Cinta.jpg', 'Cinta karena Cinta', 'Drama Roman ', '2019-08-01', 'Kisah bermula dari Jenar kembali bermimpi tentang kejadian kebakaran di rumahnya 15 tahun yang lalu. Ayah dan ibunya Halim dan Sriningsih tewas dalam peristiwa tersebut. Jenar juga mengira bahwa kakaknya Mila tewas dalam kejadian tersebut padahal kakaknya itu terluka parah dan diadopsi oleh Ayu yang kemudian namanya diganti menjadi Raisa.', 'Gita Djun', 'Natasha Wilona. Immanuel Caesar Hito. Gabriella Larasati. Megan Domani. Adjie Pangestu. Dina Lorenza. Rexy Rezky. Nunu Datau. Boy Tirayoh. Cut Keke. Inggrid Kansil. Reza Ali Syahbana. Sandrinna Michelle. Ersya Aurelia. Philip de May. Dinda Kanyadewi. Eeng Saptahadi. Triningtyas.'),
(6, '../css/assets/Dunia_Terbalik.jpeg', 'Dunia Terbalik', 'Komedi Drama', '2017-01-05', 'Dunia Terbalik mengangkat cerita tentang para suami yang ditinggalkan istrinya untuk bekerja di luar negeri. Dimulai dari kisah Akum Aceng Idoy dan Dadang. Mereka harus mendidik anak dan mengurus urusan rumah tangga yang biasanya menjadi urusan para wanita. Sementara istrinya harus menafkahi keluarga.', 'Iip S. Hanan. Depi Herlambang. Lono Abdul Hamid. Rudi Aryanto. Indrawan. Bobby Herlambang. Asep Kusdinar', 'Agus Kuncoro. Sutan Simatupang. Bambang Chandra Bayu. Indra Birowo. Mieke Amalia. Diaz Ardiawan. Guntara Hidayat. Anjani Dina. Valerie Tifanka. Rosnita Putri. Idrus Madani. Ryana Dea. Mak Enah. Faby Marcelia. Annisa Shifa MH. Qheyla Valendro. Yafi Tessa Zahara. Marsha Risdasari.'),
(7, '../css/assets/Csuperboy.jpeg', 'Cowokku Superboy', 'Drama Roman', '2014-11-16', 'Elang atau akrab dipanggil El Ciccio Manassero adalah seorang remaja berusia 17 tahun yang bersekolah di SMU Amanah. Sekilas El terlihat seperti remaja lain seusianya tetapi El ternyata memiliki kekuatan rahasia yang maha dahsyat. Hanya kedua orang tua El yaitu Tyas Angel Karamoy dan Adam Mike Lewis yang mengetahui kekuatan ini.', 'Emil G Hampp', 'Ciccio Manassero. Larasati Nugroho. Belinda Camesi. Christ Laurent. Mikaila Patritz.'),
(8, '../css/assets/Ganteng-Ganteng_Serigala.jpg', 'Ganteng-Ganteng Serigala Langit', 'Drama Laga Misteri Horror Remaja', '2014-04-21', 'Tristan bersama saudara-saudaranya adalah murid baru di salah satu International School. Tak ada yang tahu bahwa Tristan dan saudara-saudaranya yaitu Digo Yasha Liora dan Thea adalah bangsa vampir. Ayah mereka yaitu Ayah Agra mengutus Tristan untuk mencari dan mengambil darah suci yang terdapat dalam tubuh Nayla. Bila bangsa vampir mendekati pemilik darah suci mereka akan merasa kesakitan. Oleh sebab itu ayah Agra mengutus Tristan untuk mengambil darah suci itu karena Nayla sudah jatuh cinta kepada Tristan ', 'Findo Purwono HW', 'Ricky Harun. Jessica Mila. Kevin Julio. Aliando. Dicky SM*SH. Prilly Latuconsina. Dahlia Poland. Michelle Joan. Ricky Cuaca.'),
(9, '../css/assets/Hati_yang_Memilih.jpeg', 'Hati yang Memilih', 'Drama Roman Keluarga Fantasi', '0000-00-00', 'Hati yang Memilih bercerita tentang kisah seorang gadis bernama Putri yang sangat mandiri. Untuk mencari uang Putri bekerja sebaAzzam adalah seorang pemuda sederhana yang memilih untuk menuntut ilmunya di Kampus Universitas Al Azhar Kairo. Azzam dikenal sebagai sosok yang tegas dan dewasa. Dia sangat memegang teguh prinsip-prinsip Islam dalam kehidupan sehari-harinya. Di kalangan teman-temannya pun Azzam menjadi panutan dan sosok yang bisa diandalkan.', 'Bobby Moeryawan Encep Masduki', 'Amanda Manopo. Lucky Perdana. Aditya Zoni. Eza Gionino. Christ Laurent. Masayu Clara. Fadlan Muhammad. Verlita Evelyn. Susan Sameh. Rommy Sulastyo. Andi Soraya. Rebecca Tamara. Irene Librawati. Erma Zarina. Mat Rozi.'),
(10, '../css/assets/Ketika_Cinta_Bertasbih.jpg', 'Kisah Cinta Anak Tiri', 'Drama Roman', '2020-02-17', 'Diandra memiliki sifat baik hati lemah lembut dan penyayang. Ia dan adiknya Elsa hidup bahagia bersama sang ayah Harun. Namun semua itu berubah ketika Lena serta putrinya Clara masuk dalam kehidupan Diandra dan Elsa karena Harun menikahi Lena. Clara adalah gadis seusia Diandra yang memiliki tempramen suka merundung jahat iri dan tidak suka orang lain lebih darinya. Di hari pernikahan Harun dan Lena Diandra sengaja dikunci di kamar mandi.', 'Umam A.P.', 'Zoe Jackson. Aditya Zoni. Ochi Rosdiana. Icha Nabila. Dinda Mahira. Sultan Djorghi. Annisa Trihapsari. Hj. Nani Wijaya. Richelle. Sisca Magdalena. Achul Wiraperwata. Adzwa. Rizky Djanbi. Jeremie Moeremans. Indah Setyani.'),
(11, '../css/assets/Melati_Untuk_Marvel.jpg', 'Melati untuk Marvel', 'Drama Roman', '2008-10-23', 'Melati gadis berusia 22 tahun jodoh adalah urutan ke sekian setelah pekerjaan. Melati sendiri adalah sosok yang mandiri tegas dan bertanggung jawab. Ditunjang oleh penampilan fisik yang menarik tak heran jika banyak cowok yang jatuh hati padanya.', 'Akbar Bhakti', 'Chelsea Olivia. Rezky Aditya. Christ Laurent. Neshia Putri. Fendy Chow. Gracia Indri. Afifa Syahira. Ryan Delon.'),
(12, 'pertemuan 12.png', 'sda', 'dsad', '2023-06-03', 'dsa', 'dsa', 'dsad');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `drama`
--
ALTER TABLE `drama`
  ADD PRIMARY KEY (`id_drama`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

CREATE TABLE drama
(
    id_drama	INT,
    gambar	VARCHAR(512),
    judul	VARCHAR(512),
    genre	VARCHAR(512),
    tanggal_tayang	VARCHAR(512),
    sinopsis	VARCHAR(512),
    sutradara	VARCHAR(512),
    pemeran	VARCHAR(512)
);

INSERT INTO drama(id_drama, gambar, judul, genre, tanggal_tayang, sinopsis, sutradara, pemeran) VALUES ('1', '../css/assets/Anak-jalanan.jpeg', 'Anak Jalanan', 'Drama Roman Laga', '2015-10-12', 'Anak Jalanan: A New Beginning menceritakan tentang seorang anak geng motor bernama Boy yang jatuh cinta dengan seorang gadis bernama Reva Semenjak bertemu dengan Reva hidupnya berubah namun kisah cinta mereka tidak berjalan mulus dengan banyaknya tantangan dari orang-orang di sekitarnya.', 'Akbar Bhakti', 'Natasha Wilona. Ammar Zoni. Cut Meyriska. Immanuel Caesar Hito. Raya Kitty. Ranty Maria. Marcella Daryanani. Gerald Yo. Angga Putra. Cemal Faruk. Mischa Chandrawinata. Hana Saraswati. Adipura.Umar Lubis. Fathir Muchtar. Yoelitta Palar. Devi Permatasari. Meriam.');
INSERT INTO drama(id_drama, gambar, judul, genre, tanggal_tayang, sinopsis, sutradara, pemeran) VALUES ('2', '../css/assets/Ayat-Ayat_Cinta.jpg', 'Ayat-Ayat Cinta', 'Roman Drama', '2008-02-28', 'Ini adalah kisah cinta. Tapi bukan cuma sekadar kisah cinta yang biasa. Ini tentang bagaimana menghadapi turun-naiknya persoalan hidup dengan cara Islam. Fahri bin Abdillah adalah pelajar Indonesia yang berusaha menggapai gelar masternya di Al-Azhar. Berjibaku dengan panas-debu Mesir. Berkutat dengan berbagai macam target dan kesederhanaan hidup. Bertahan dengan menjadi penerjemah buku-buku agama. Semua target dijalani Fahri dengan penuh antusias kecuali satu: menikah.Fahri adalah laki-laki taat yang begitu lurus. Dia tidak mengenal pacaran sebelum menikah. Dia kurang artikulatif saat berhadapan dengan makhluk bernama perempuan. Hanya ada sedikit perempuan yang dekat dengannya selama ini. Neneknya Ibunya dan saudara perempuannya.Pindah ke Mesir membuat hal itu berubah. Tersebutlah Maria Girgis. ', 'Hanung Bramantyo', 'Fedi Nuril. Rianti Cartwright. Carissa Putri. Zaskia Adya Mecca. Melanie Putria. Surya Saputra. Oka Antara. Dennis Adhiswara');
INSERT INTO drama(id_drama, gambar, judul, genre, tanggal_tayang, sinopsis, sutradara, pemeran) VALUES ('3', '../css/assets/Bintang-Di-Hatiku.jpg', 'Bintang di Hatiku', 'Drama Keluarga', '2017-04-03', 'Murti Intan Nuraini merupakan ibu dari empat orang anak yang bernama Selly Bagus Poppy dan Lolly. Ia berjumpa dengan Jaka (Sonny Septian) yang mengatakan akan menikahinya dan menerima keempat anak-anak Murti. Jaka pada suatu hari meminta Murti untuk hadir ke Jakarta sendirian. Murti kemudian meninggalkan anak-anaknya bersama ibu Murti di desa. Namun Jaka menyuruh seseorang untuk membakar rumah Murti tersebut sehingga menyebabkan ibu Murti meninggal. Keempat anaknya kemudian berangkat ke Jakarta untuk mencari ibunya tetapi tanpa hasil. Sementara itu Murti yang merasa ditipu oleh Jaka kabur dan kembali ke desa. Ia menyadari bahwa ia tidak menemukan anak-anaknya di sana dan kembali ke Jakarta untuk mencari mereka.', 'Bobby Moeryawan', 'Intan Nuraini. Haura Lathifa. Jerico Septian Gowtama. Ciara Brosnan. Aditya Firmansyah. Sonny Septian. Adelia Rasya. Nisya Ahmad. Teuku Mirza. Rayhan Cornelis');
INSERT INTO drama(id_drama, gambar, judul, genre, tanggal_tayang, sinopsis, sutradara, pemeran) VALUES ('4', '../css/assets/Cinta_Fitri_New.jpg', 'Cinta Fitri', 'Drama Roman Keluarga Religi', '2007-04-02', 'Cinta Fitri menjadi salah satu sinetron kebanggaan yang ditayangkan oleh stasiun televisi SCTV kemudian pindah ke Indosiar karena alur ceritanya yang padat menarik dan kadang-kadang tidak terduga apa lanjutannya. Ini juga menjadi kunci kesuksesan Cinta Fitri sehingga bisa bertahan hingga musim ke 7 dan tayang selama 4 tahun dari tahun 2007 hingga 2011 dan walaupun setelah Cinta Fitri Season Ramadhan selesai tayang beberapa orang mulai mengkritik jalan cerita Cinta Fitri yang terlihat semakin dibuat-buat dan tidak sebaik jalan cerita season-season sebelumnya kenyataannya Cinta Fitri Season 5 justru lebih banyak mendapat pujian dan dalam sekejap menduduki rating tertinggi. Ini menandakan bahwa Cinta Fitri memang masih digemari oleh masyarkat Indonesia.', 'H. Encep Masduki', 'Shireen Sungkar. Teuku Wisnu. Adly Fairuz. Donita. Verlita Evelyn. Iqbal Pakula. Dinda Kanyadewi. Sandy Syarief. Nuri Maulid. Lian Firman. Irene Librawati. Meidiana Hutomo');
INSERT INTO drama(id_drama, gambar, judul, genre, tanggal_tayang, sinopsis, sutradara, pemeran) VALUES ('5', '../css/assets/Cinta_karena_Cinta.jpg', 'Cinta karena Cinta', 'Drama Roman ', '2019-08-01', 'Kisah bermula dari Jenar kembali bermimpi tentang kejadian kebakaran di rumahnya 15 tahun yang lalu. Ayah dan ibunya Halim dan Sriningsih tewas dalam peristiwa tersebut. Jenar juga mengira bahwa kakaknya Mila tewas dalam kejadian tersebut padahal kakaknya itu terluka parah dan diadopsi oleh Ayu yang kemudian namanya diganti menjadi Raisa.', 'Gita Djun', 'Natasha Wilona. Immanuel Caesar Hito. Gabriella Larasati. Megan Domani. Adjie Pangestu. Dina Lorenza. Rexy Rezky. Nunu Datau. Boy Tirayoh. Cut Keke. Inggrid Kansil. Reza Ali Syahbana. Sandrinna Michelle. Ersya Aurelia. Philip de May. Dinda Kanyadewi. Eeng Saptahadi. Triningtyas.');
INSERT INTO drama(id_drama, gambar, judul, genre, tanggal_tayang, sinopsis, sutradara, pemeran) VALUES ('6', '../css/assets/Dunia_Terbalik.jpeg', 'Dunia Terbalik', 'Komedi Drama', '2017-01-05', 'Dunia Terbalik mengangkat cerita tentang para suami yang ditinggalkan istrinya untuk bekerja di luar negeri. Dimulai dari kisah Akum Aceng Idoy dan Dadang. Mereka harus mendidik anak dan mengurus urusan rumah tangga yang biasanya menjadi urusan para wanita. Sementara istrinya harus menafkahi keluarga.', 'Iip S. Hanan. Depi Herlambang. Lono Abdul Hamid. Rudi Aryanto. Indrawan. Bobby Herlambang. Asep Kusdinar', 'Agus Kuncoro. Sutan Simatupang. Bambang Chandra Bayu. Indra Birowo. Mieke Amalia. Diaz Ardiawan. Guntara Hidayat. Anjani Dina. Valerie Tifanka. Rosnita Putri. Idrus Madani. Ryana Dea. Mak Enah. Faby Marcelia. Annisa Shifa MH. Qheyla Valendro. Yafi Tessa Zahara. Marsha Risdasari.');
INSERT INTO drama(id_drama, gambar, judul, genre, tanggal_tayang, sinopsis, sutradara, pemeran) VALUES ('7', '../css/assets/Csuperboy.jpeg', 'Cowokku Superboy', 'Drama Roman', '2014-11-16', 'Elang atau akrab dipanggil El Ciccio Manassero adalah seorang remaja berusia 17 tahun yang bersekolah di SMU Amanah. Sekilas El terlihat seperti remaja lain seusianya tetapi El ternyata memiliki kekuatan rahasia yang maha dahsyat. Hanya kedua orang tua El yaitu Tyas Angel Karamoy dan Adam Mike Lewis yang mengetahui kekuatan ini.', 'Emil G Hampp', 'Ciccio Manassero. Larasati Nugroho. Belinda Camesi. Christ Laurent. Mikaila Patritz.');
INSERT INTO drama(id_drama, gambar, judul, genre, tanggal_tayang, sinopsis, sutradara, pemeran) VALUES ('8', '../css/assets/Ganteng-Ganteng_Serigala.jpg', 'Ganteng-Ganteng Serigala Langit', 'Drama Laga Misteri Horror Remaja', '2014-04-21', 'Tristan bersama saudara-saudaranya adalah murid baru di salah satu International School. Tak ada yang tahu bahwa Tristan dan saudara-saudaranya yaitu Digo Yasha Liora dan Thea adalah bangsa vampir. Ayah mereka yaitu Ayah Agra mengutus Tristan untuk mencari dan mengambil darah suci yang terdapat dalam tubuh Nayla. Bila bangsa vampir mendekati pemilik darah suci mereka akan merasa kesakitan. Oleh sebab itu ayah Agra mengutus Tristan untuk mengambil darah suci itu karena Nayla sudah jatuh cinta kepada Tristan maka Tristan bisa mendekati Nayla tanpa rasa sakit.', 'Findo Purwono HW', 'Ricky Harun. Jessica Mila. Kevin Julio. Aliando. Dicky SM*SH. Prilly Latuconsina. Dahlia Poland. Michelle Joan. Ricky Cuaca.');
INSERT INTO drama(id_drama, gambar, judul, genre, tanggal_tayang, sinopsis, sutradara, pemeran) VALUES ('9', '../css/assets/Hati_yang_Memilih.jpeg', 'Hati yang Memilih', 'Drama Roman Keluarga Fantasi', '2007', 'Hati yang Memilih bercerita tentang kisah seorang gadis bernama Putri yang sangat mandiri. Untuk mencari uang Putri bekerja sebaAzzam adalah seorang pemuda sederhana yang memilih untuk menuntut ilmunya di Kampus Universitas Al Azhar Kairo. Azzam dikenal sebagai sosok yang tegas dan dewasa. Dia sangat memegang teguh prinsip-prinsip Islam dalam kehidupan sehari-harinya. Di kalangan teman-temannya pun Azzam menjadi panutan dan sosok yang bisa diandalkan.', 'Bobby Moeryawan Encep Masduki', 'Amanda Manopo. Lucky Perdana. Aditya Zoni. Eza Gionino. Christ Laurent. Masayu Clara. Fadlan Muhammad. Verlita Evelyn. Susan Sameh. Rommy Sulastyo. Andi Soraya. Rebecca Tamara. Irene Librawati. Erma Zarina. Mat Rozi.');
INSERT INTO drama(id_drama, gambar, judul, genre, tanggal_tayang, sinopsis, sutradara, pemeran) VALUES ('10', '../css/assets/Ketika_Cinta_Bertasbih.jpg', 'Kisah Cinta Anak Tiri', 'Drama Roman', '2020-02-17', 'Diandra memiliki sifat baik hati lemah lembut dan penyayang. Ia dan adiknya Elsa hidup bahagia bersama sang ayah Harun. Namun semua itu berubah ketika Lena serta putrinya Clara masuk dalam kehidupan Diandra dan Elsa karena Harun menikahi Lena. Clara adalah gadis seusia Diandra yang memiliki tempramen suka merundung jahat iri dan tidak suka orang lain lebih darinya. Di hari pernikahan Harun dan Lena Diandra sengaja dikunci di kamar mandi.', 'Umam A.P.', 'Zoe Jackson. Aditya Zoni. Ochi Rosdiana. Icha Nabila. Dinda Mahira. Sultan Djorghi. Annisa Trihapsari. Hj. Nani Wijaya. Richelle. Sisca Magdalena. Achul Wiraperwata. Adzwa. Rizky Djanbi. Jeremie Moeremans. Indah Setyani.');
INSERT INTO drama(id_drama, gambar, judul, genre, tanggal_tayang, sinopsis, sutradara, pemeran) VALUES ('11', '../css/assets/Melati_Untuk_Marvel.jpg', 'Melati untuk Marvel', 'Drama Roman', '2008-10-23', 'Melati gadis berusia 22 tahun jodoh adalah urutan ke sekian setelah pekerjaan. Melati sendiri adalah sosok yang mandiri tegas dan bertanggung jawab. Ditunjang oleh penampilan fisik yang menarik tak heran jika banyak cowok yang jatuh hati padanya.', 'Akbar Bhakti', 'Chelsea Olivia. Rezky Aditya. Christ Laurent. Neshia Putri. Fendy Chow. Gracia Indri. Afifa Syahira. Ryan Delon.');
INSERT INTO drama(id_drama, gambar, judul, genre, tanggal_tayang, sinopsis, sutradara, pemeran) VALUES ('12', '../css/assets/Anak-Langit.jpeg', 'Anak Langit', 'Laga Roman Drama', '2017-02-20', 'Al Andra dan Key tinggal di Panti Asuhan milik Babe Rozak dan Nyak Ida. Mereka bertiga memiliki kepribadian yang berbeda tetapi saling melengkapi. Mereka tergabung dalam sebuah geng motor Rainbow. Salah satu anggota Rainbow bernama Reno yang telah meninggal menitipkan adiknya Vika kepada Al. Seiring berjalannya waktu Al menaruh hati pada Vika. Namun Rimba yang merupakan ketua geng motor Anthrax yang tak lain adalah musuh besar Al berusaha menarik hati Vika.', 'Akbar Bhakti', 'Stefan William. Marcella Daryanani. Hana Saraswati. Anthony Xie. Gerald Yo. Mario Maulana. Raya Kitty. Fathir Muchtar. Fera Feriska. Umar Lubis. Devi Permatasari. Angga Putra. Leon Dozan. Mezty Mez. Benny Ruswandi. Henny Timbul. Sasha Alexa. Merry Mustaf. Adipura. Aldo Bamar. Siska Magdalena. Firman Maliksyah. Audi Marissa. Fanny Fadillah. Cassandra Lee. George Rudy. Fendy Pradana. Kevin Kambey. Natalie Zenn. Esta Pramanita. Ije Kurniawan. Teuku Anwar. Willy Dozan.');

